# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # about ----
  - name:   '<i class="far fa-question-circle"></i> &nbsp; About MBON'
    url:    'about_mbon'
    weight: 10
  - name:   'Timeline'
    weight: 20
    parent: '<i class="far fa-question-circle"></i> &nbsp; About MBON'
    url:    'about/timeline'
  - name:   'People'
    weight: 30
    parent: '<i class="far fa-question-circle"></i> &nbsp; About MBON'
    url:    'about/people'
  - name:   'Strategy and Implementation'
    weight: 40
    parent: '<i class="far fa-question-circle"></i> &nbsp; About MBON'
    url:    'about/strategy_and_implementation'
  # network and projects ----
  - name:   '<i class="fas fa-project-diagram"></i> &nbsp; The Network'
    weight: 20
    url:    'network'
  - name:   'Network Structure'
    weight: 10
    parent: '<i class="fas fa-project-diagram"></i> &nbsp; The Network'
    url:    'network'
  - name:   'Projects'
    weight: 20
    parent: '<i class="fas fa-project-diagram"></i> &nbsp; The Network'
    url:    '#projects'
  # data and products ----
  - name:   '<i class="fas fa-tools"></i> &nbsp; Data and Products'
    url:    '#products'
    weight: 30
  # news_events ----
  - name:   '<i class="far fa-newspaper"></i> &nbsp; News'
    url:    '/post/'
    weight: 40
  # news_events ----
  - name:   '<i class="fas fa-book"></i> &nbsp; Publications'
    url:    '/publication/'
    weight: 50
  # contacts ----
  - name:   '<i class="far fa-address-card"></i> &nbsp; Contacts'
    url:    '/contacts'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
